const hobbies = [
    "// THIS CODE GENERATES MY HOBBIES",
    "",
    "class hobbies{",
    "    Node top;",
    "",
    "    public class Node {",
    "        String data;",
    "        Node next;",
    "",
    "        Node(String x) {",
    "            data = x;",
    "            next = null;",
    "        }",
    "    }",
    "",
    "    public void push(String data) {",
    "        Node temp = new Node(data);",
    "        temp.next = top;",
    "        top = temp;",
    "    }",
    "",
    "    public void pop() {",
    "        top = top.next;",
    "    }",
    "",
    "    public void display() {",
    "        Node temp = top;",
    "        while (temp != null) {",
    "            System.out.println(temp.data);",
    "            temp = temp.next;",
    "        }",
    "        System.out.println(\" \");",
    "    }",
    "",
    "    public static void main(String[] args){",
    "        hobbies h = new hobbies();",
    "        h.push(\"hobby1\");",
    "        h.push(\"hobby2\");",
    "        h.push(\"hobby3\");",
    "        h.display();",
    "        h.pop();",
    "        h.display();",
    "    }",
    "}"
]

export default hobbies;